name: Docker build containers & push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_django_job:
    uses: AbelHristodor/django-k8s-tutorial/.github/workflows/test-django.yaml@main
  build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      DJANGO_SECRET_KEY: test-key
      CLUSTER_NAME: django-k8s
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_TOKEN_KEY }}
    - name: Login to DO Container Registry with short-lived creds
      run: doctl registry login --expiry-seconds 1200
    - name: Build container
      working-directory: ./web
      run: |
        docker build -f Dockerfile \
          -t registry.digitalocean.com/test-k8s/django-k8s-web:latest \
          -t registry.digitalocean.com/test-k8s/django-k8s-web:${GITHUB_SHA::7} \
          .
    - name: Push to container registry
      run: |
        docker push registry.digitalocean.com/test-k8s/django-k8s-web --all-tags
    - name: K8s cluster kubeconfig file short-lived creds
      run: |
        doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
    - name: Update Deployment secrets
      run: |
        cat << EOF >> web/.env.prod

        DJANGO_SUPERUSER_USERNAME=${{secrets.DJANGO_SUPERUSER_USERNAME}}
        DJANGO_SUPERUSER_PASSWORD=${{secrets.DJANGO_SUPERUSER_PASSWORD}}
        DJANGO_SUPERUSER_EMAIL=${{secrets.DJANGO_SUPERUSER_EMAIL}}
        DJANGO_SECRET_KEY=${{secrets.DJANGO_SECRET_KEY}}
        POSTGRES_DB=${{secrets.POSTGRES_DB}}
        POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}
        POSTGRES_USER=${{secrets.POSTGRES_USER}}
        POSTGRES_HOST=${{secrets.POSTGRES_HOST}}
        POSTGRES_PORT=${{secrets.POSTGRES_PORT}}
        POSTGRES_READY=${{secrets.POSTGRES_READY}}
        ENV_ALLOWED_HOSTS=${{secrets.ENV_ALLOWED_HOSTS}}
        REDIS_HOST=${{secrets.REDIS_HOST}}
        REDIS_PORT=${{secrets.REDIS_PORT}}

        EOF
        kubectl delete django-k8s-web-prod-env
        kubectl create secret generic django-k8s-web-prod-env --from-env-file=web/.env.prod
    - name: Update Deployment image
      run: |
        kubectl set image deployment/django-k8s-web-deployment django-k8s-web=registry.digitalocean.com/test-k8s/django-k8s-web:${GITHUB_SHA::7}
    - name: Wait for Rollout to finish
      run: |
        kubectl rollout status deployment/django-k8s-web-deployment
    - name: Migrate Database
      run: |
        export SINGLE_POD_NAME=$(kubectl get pod -l app=django-k8s-web-deployment -o jsonpath="{.items[0].metadata.name}")
        kubectl exec -it $SINGLE_POD_NAME -- bash /app/migrate.sh
